### ISSUE TITLE
Run Stryker CI/CD and other frontend tests only when frontend changes

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156-f22/f22-5pm-happycows#19]
In the file `.github/workflows/34-frontend-mutation-testing.yml` we can change:

```
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
```
To this:

```
on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [ main ]
    paths: [frontend/**]
```
With this syntax, the job only runs when there is a change to some file under the frontend directory.

This should speed things up when a PR only affects the backend, since we won't need to run Stryker again (which can take a very long time.)

You can then make the same changes to all these jobs as well:

.github/workflows/30-frontend-tests.yml
.github/workflows/32-frontend-coverage.yml
.github/workflows/36-frontend-eslint.yml
And for the job that tests on the backend, we can do something similar:

.github/workflows/10-backend-unit.yml
.github/workflows/12-backend-jacoco.yml
.github/workflows/14-backend-pitest.yml
We can use:
  - paths: [src/**, pom.xml, lombok.config]
